import type { Product } from "./types"

export const sampleProducts: Product[] = [
  {
    id: "1",
    title: "Midnight Vibes",
    price: 29.99,
    bpm: 140,
    key: "Am",
    tags: ["trap", "dark", "atmospheric"],
    audioUrl: "/placeholder.mp3",
    imageUrl: "/dark-atmospheric-beat-cover.png",
    description:
      "A dark, atmospheric trap beat perfect for late-night sessions. Features haunting melodies and hard-hitting drums.",
    type: "beat",
    duration: "3:24",
    genre: "Trap",
    mood: "Dark",
    featured: true,
  },
  {
    id: "2",
    title: "Golden Hour",
    price: 24.99,
    bpm: 85,
    key: "C",
    tags: ["chill", "lo-fi", "warm"],
    audioUrl: "/placeholder.mp3",
    imageUrl: "/golden-hour-beat-cover.png",
    description: "Warm, chill lo-fi beat with smooth jazz influences. Perfect for relaxed vocals and storytelling.",
    type: "beat",
    duration: "2:45",
    genre: "Lo-Fi",
    mood: "Chill",
    featured: true,
  },
  {
    id: "3",
    title: "Urban Dreams",
    price: 34.99,
    bpm: 128,
    key: "Gm",
    tags: ["hip-hop", "urban", "modern"],
    audioUrl: "/placeholder.mp3",
    imageUrl: "/urban-hip-hop-beat-cover.png",
    description: "Modern hip-hop beat with crisp drums and melodic elements. Great for contemporary rap styles.",
    type: "beat",
    duration: "3:12",
    genre: "Hip-Hop",
    mood: "Energetic",
  },
  {
    id: "4",
    title: "Trap Essentials Vol. 1",
    price: 49.99,
    bpm: 0,
    key: "Various",
    tags: ["trap", "samples", "drums"],
    audioUrl: "/placeholder.mp3",
    imageUrl: "/placeholder-hiwql.png",
    description: "Complete trap sample pack with 50+ high-quality samples including drums, melodies, and FX.",
    type: "sample-pack",
    duration: "50 samples",
    genre: "Trap",
    mood: "Various",
  },
  {
    id: "5",
    title: "Neon Nights",
    price: 27.99,
    bpm: 110,
    key: "Em",
    tags: ["synthwave", "retro", "electronic"],
    audioUrl: "/placeholder.mp3",
    imageUrl: "/neon-synthwave-beat-cover.png",
    description: "Retro synthwave beat with nostalgic vibes and modern production. Perfect for atmospheric tracks.",
    type: "beat",
    duration: "3:56",
    genre: "Synthwave",
    mood: "Nostalgic",
  },
  {
    id: "6",
    title: "Bass Heavy",
    price: 32.99,
    bpm: 150,
    key: "Dm",
    tags: ["bass", "heavy", "aggressive"],
    audioUrl: "/placeholder.mp3",
    imageUrl: "/heavy-bass-beat-cover.png",
    description: "Hard-hitting beat with massive 808s and aggressive percussion. Built for high-energy performances.",
    type: "beat",
    duration: "2:58",
    genre: "Trap",
    mood: "Aggressive",
  },
  {
    id: "7",
    title: "Smooth Jazz Fusion",
    price: 39.99,
    bpm: 95,
    key: "Bb",
    tags: ["jazz", "smooth", "fusion"],
    audioUrl: "/placeholder.mp3",
    imageUrl: "/smooth-jazz-beat-cover.png",
    description: "Sophisticated jazz-influenced beat with smooth chord progressions and live instrument samples.",
    type: "beat",
    duration: "4:12",
    genre: "Jazz",
    mood: "Smooth",
  },
  {
    id: "8",
    title: "R&B Soul Pack",
    price: 44.99,
    bpm: 0,
    key: "Various",
    tags: ["rnb", "soul", "vocals"],
    audioUrl: "/placeholder.mp3",
    imageUrl: "/rnb-soul-sample-pack.png",
    description: "Premium R&B sample pack featuring soulful vocals, smooth basslines, and vintage drum breaks.",
    type: "sample-pack",
    duration: "35 samples",
    genre: "R&B",
    mood: "Soulful",
  },
]
